"""
Django settings for MusicControl project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!fsv2&&mdy$dz_zqk+g&nbyo6=cq4cz(o6=1!l)a9f2*uq=4hu'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "app.middlewares.vfcode.VfcodeViewMiddleware",
    "app.middlewares.check_single_login.LoginViewMiddleware",
]

ROOT_URLCONF = 'MusicControl.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'MusicControl.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # 选择数据库引擎
        'NAME': 'musiccontrol',
        'HOST': '172.10.5.208',
        'PORT': '3306',
        'USER': 'root',
        'PASSWORD': '123456',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# 1111
# # SESSION_ENGINE="redis_sessions.session"
#
#
# # DJango1.x  2.x
# # SESSION_REDIS_HOST = "101.200.140.225"
# # SESSION_REDIS_PORT = 6379
# # SESSION_REDIS_DB = 0
# # SESSION_REDIS_PASSWORD = "123456"
# # SESSION_REDIS_PREFIX = "session"
#
# # SESSION_REDIS={
# #     "host":"172.20.4.20",
# #     "port":6379,
# #     "db":0,
# #     # "password":"123456",
# #     "prefix":"session",
# #     "socket_time":10
# # }
#
# #从缓存中读取存的session
# # CACHES = {
# #     'default': {
# #         'BACKEND': 'django_redis.cache.RedisCache',
# #         'LOCATION': 'redis://172.20.4.20:6379',
# #         "OPTIONS": {
# #             "CLIENT_CLASS": "django_redis.client.DefaultClient",
# #              # "PASSWORD": "yoursecret",
# #         },
# #     },
# # }
# 1111
#
# # REDIS_TIMEOUT=7*24*60*60
# # CUBES_REDIS_TIMEOUT=60*60
# # NEVER_REDIS_TIMEOUT=365*24*60*60

#redis缓存
CACHES={
    "default":{
        "BACKEND":"redis_cache.cache.RedisCache" ,#说明存储位置
        "TIMEOUT":60,  #设置缓存时间  1.非零正整数，单位是秒2.不写，默认300秒3.None，永不过期4.0:立即过期
        "LOCATION":"172.10.5.208:6379",
        "OPTIONS":{
            # "PASSWORD":"123456"
        }
    }
}