# Generated by Django 3.2 on 2023-10-14 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('context', models.CharField(max_length=100)),
                ('callNum', models.IntegerField()),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'music_list',
            },
        ),
        migrations.CreateModel(
            name='MusicType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'music_type',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('nickname', models.CharField(max_length=10, unique=True)),
                ('cardNum', models.IntegerField()),
                ('isDelete', models.BooleanField(default=False)),
                ('music_id', models.ManyToManyField(to='app.MusicList')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='musiclist',
            name='music_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.musictype'),
        ),
        migrations.CreateModel(
            name='MusicComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=100)),
                ('music_comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.musiclist')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
